language: node_js
node_js: node
addons:
  firefox: latest
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
deploy:
  skip_cleanup: true
  provider: heroku
  app: quiet-harbor-29786
  api_key: >-
    l05CshuH6VLp6Za/2Q5CCYQsFsby6DrZyjKHHduGdu2dcx8iCftyrROTczrnXC8eAoQcoULFpzKWOd+zM10PIZfMScK6BgleA9PRcQK3UbGxqtCcnGOKdzoUElc7ksb/y9Wpf1uJeSHh+qbj1Inw/x2HdeAIjsMF4NNWReyTFSvaDSPWfodTWbW6cM8fXN6DqIelvmsMFp62JVqtcBR+R7KztAT5W/RysdSSGBLA7ssqz6LIUC3IXVp/3g1pOlaeIjHjtqgea5b7fSJcW8HrWUZr43ry4nUagi13j91GJdYiCK9G+v1gH5BlP8M5IeLbSosMwqHKnSDHb+MEvMR8NldJQ8hBTOc1OHZQWCB4Sgu01pkvuEKY85jatB2YIK68HVBsG5qyVabeql7wggAx2nuMxowI4MwvOQrR/9jdSKV0J4mKeLFAhb3ZQP4kjOjkhlKJHUyi1WfKvLVDn+LRN2UGZ6/jQVTcj64XXSif4XP87Dcni0stJI99iS+AAJLWvlWxLDnzHN2xB39iSK/cE1M9o254G7h5plaXj0L+QzDysYG3Z+IhMfVWxR+MZntyJ7TT/of0SxnLu8OKBaU8Kzq7hjcMPCtgUOfyJYBR1q6wHFb2nxxPv3Y1yG/GDDVWwXtUIX7KlAHTxN6ID7cVNA+iFoq42/+csYZ2xyAboY0=
before_deploy:
  - git config --global user.email "me@example.com"
  - git config --global user.name "deploy bot"
  - node build
  - git add dist/ --force
  - git commit -m "Updating build."
  - 'npm run deploy:ci'
env:
  global:
    - secure: >-
        hqWjtKx8YRpHbTeX8IvAQ8GLUI/xp5ipGk5dZ9RzUXKBdbBzJKBW5F5e/zVOqLkkIfORsOuLCo+98ws8v3ZxZtrVsgmW6zgyDKEkiBksjcCqHcCgTAMGGWQyUQqF1iJes8djxYNzZj/LKEOaZAavZml0KgpB/StQgzz5Ddr93FhiLdTWu+zjzC5XO0MrzCb2M7P+6gE0j21PrLZEF5FOAgV3tuPe3UEhPLtid0GQ/qcuXljIRWohNfyYbvQ0fAe4EakRhjnD6M76qEytzjprUZW4S6mOQraQJkkdFJKyCaMe/P3PPRAGx3/q+cBxcOb3lH8VP8794LhfoC2djvPX1cK1HG1WN5rZeCjqWDydX7f0I+MQDwd3UzoiRP/arYWhOOKrIxLlkWplT5mCkuAJcw/IhAzBBn22OCwShFEBW8gx9zFJktRPzh0ibD/nyVf1XhvShfsaHQsfkKmVOYcbV/X465CrxyA9pQhgO7vQlAkI5/+sE1ueWk3tpBHt+8I5DbICDODJZcw6GJpDTTVZ6/jMHpDC8TcKzyFrGC4BFNxE61REJ1v+nYQ5T6xFcMuApjNAI9IlUPdFTwnPkelr8rx/H8QUqj/XI3v9wXOf9bbzt4Z8r/bf20fzOQBYrevAJFkf/TZqer1Ewia6MZ5VmMTjS2Dm6pHe2cdfFNAaSag=
