language: node_js
node_js: node
addons:
  firefox: latest
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
deploy:
  skip_cleanup: true
  provider: heroku
  app: quiet-harbor-29786
  api_key: >-
    l05CshuH6VLp6Za/2Q5CCYQsFsby6DrZyjKHHduGdu2dcx8iCftyrROTczrnXC8eAoQcoULFpzKWOd+zM10PIZfMScK6BgleA9PRcQK3UbGxqtCcnGOKdzoUElc7ksb/y9Wpf1uJeSHh+qbj1Inw/x2HdeAIjsMF4NNWReyTFSvaDSPWfodTWbW6cM8fXN6DqIelvmsMFp62JVqtcBR+R7KztAT5W/RysdSSGBLA7ssqz6LIUC3IXVp/3g1pOlaeIjHjtqgea5b7fSJcW8HrWUZr43ry4nUagi13j91GJdYiCK9G+v1gH5BlP8M5IeLbSosMwqHKnSDHb+MEvMR8NldJQ8hBTOc1OHZQWCB4Sgu01pkvuEKY85jatB2YIK68HVBsG5qyVabeql7wggAx2nuMxowI4MwvOQrR/9jdSKV0J4mKeLFAhb3ZQP4kjOjkhlKJHUyi1WfKvLVDn+LRN2UGZ6/jQVTcj64XXSif4XP87Dcni0stJI99iS+AAJLWvlWxLDnzHN2xB39iSK/cE1M9o254G7h5plaXj0L+QzDysYG3Z+IhMfVWxR+MZntyJ7TT/of0SxnLu8OKBaU8Kzq7hjcMPCtgUOfyJYBR1q6wHFb2nxxPv3Y1yG/GDDVWwXtUIX7KlAHTxN6ID7cVNA+iFoq42/+csYZ2xyAboY0=
before_deploy:
  - git config --global user.email "me@example.com"
  - git config --global user.name "deploy bot"
  - node build
  - git add dist/ --force
  - git commit -m "Updating build."
  - 'npm run deploy:ci'
env:
  global:
    - secure: >-
        VcRhJLJ/Qn/vwULjurw1WbId2lbG6RJNcgu1WpZa+HYsDz3EP5ZrDB1s2De4b/3d2mPxe2Nucn/abEEpyfN8t6jULdRnACloZ81Swl5EY6t3BSPui91q2ABZrxH/O+UXyX7qrq8NHvmIsfCYmsgQ2SSXXgaj6glB5b/bZYsOjW+411fBHagKFwUEXIs99LqkpKYG73EikkM44SpkS5Q4eDa/EYXLwS3+OdogKctS6zCthFumm5mmROrt/Wp21RlWTNV+FY4ch8TDuXX5jOi6SsvdRrsRo32THKX0x5OQMfF0t2F0tht5k8ofOIW+wThxmLXDPbvKScJniHGId+f2BrqVPNikQIflUhAjd5gwQcXkRuTxelq0g/NbADzeYLRGO3fNvMI0o+oSqKPc2J2Q6sXP4sUFJpabcsvpkO0F6Q2SiVkcWn38N30Gouq4zxchnXFFEqwJ0JW30g460eQr7MZwlmpKjf4hx3F2j95VXu2qbpn0OisLVeRQt9bhbhZkrqi9faXE+dPIwWNDyuSRA/z+ZXVy2uY7dKnpIarL24nlCE6EsY5y1x1uuhFfBdY7zjhKYWgZz1AFD473ieE+czqjF2b+eKniX1PXzg++hhmtyIe2yo8U6GIV+7jl0MaCcqtva2Cm+SZsFJ83c1OCFwAZ7OuPlMMsg/a4mBbY7YA=
